### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by hexistore** [leeyiw/dnspod_ddns#1]
[2015-04-17 19:35:47,616 INFO] Starting new HTTPS connection (1): dnsapi.cn
/usr/lib/python2.6/site-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

这个要怎么解决

**Comment by leeyiw** [comment]
请问这个导致ddns功能无法正常运行了吗？还是警告信息？

**Comment by leeyiw** [comment]
麻烦留一下您的python版本号，谢谢

**Comment by leeyiw** [comment]
根据您提供的信息，初步判断是python 2.7.9版本以下的urllib3在发起SSL请求的时候都会报这个错误。参见：[urllib3文档](https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning)。因此，解决方案是：**升级Python版本至2.7.9**

如果您还有别的问题，请回复一并告知，谢谢！

**Comment by hexistore** [comment]
Python 2.6.6

我也查到了，现在只是警告，可以正常更新，那我更新下版本，再试试
